config/routes.rb
SlobodnaPolica::Application.routes.draw do
  get "sessions/new"

  get "sessions/destroy"

  get "books/index"

  root :to => 'Books#index'
  resources :books
  resources :sessions

match "/login" => "sessions#new", :as => :login  
match "/logout" => "sessions#destroy", :as => :logout  

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :info, :title, :webpage, :lang, :categories, :image, :remote_image_url, :remove_image
  validates :author, presence: true 
  validates :info, presence: true 
  validates :title, presence: true
  validates :webpage, presence: true

  mount_uploader :image, ImageUploader

before_save :smart_add_url_protocol

protected

def smart_add_url_protocol
   unless self.webpage[/^(http?|https):\//]
    self.webpage = 'http://' + self.webpage
  end
end

include PgSearch
  pg_search_scope :search_by_book, 
  				:against => [:author, :info, :title, :lang, :categories],
                  :using => {
                      :tsearch => {:prefix => true, :any_word => true}
                    }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper :all
  helper_method :admin?

protected

	def admin?
	  session[:password] == "d93c22dc148e2e86051d4315e4007e25d13b221052182fca5e0d56d86d62b6a9"
	end

	def authorize
	  unless admin?
	    flash[:error] = "Zabranjen pristup, potrebne administratorske privilegije"
	    redirect_to root_path
	    false
	  end
	end

	def authorized
	  if admin?
	    flash[:error] = "Vec ste prijavljeni, imate potrebne administratorske privilegije"
	    redirect_to root_path
	    false
	  end
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :authorize, :except => [:index, :show, :new]


  def index
    if !params[:search].blank?
  	 books = Book.search_by_book( params[:search] )
      if books.empty?
        flash[:info] = 'Nema rezultata pretrage. Molimo vas pokusajte ponovo.'
        redirect_to root_path
       else
        @books = books.paginate(:page => params[:page], :per_page => 10)
      end
    else
      @books = Book.paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
    end
  end

  def show
    @book = Book.find params[:id]   
  end

  def new
    @book = Book.new
  end

  def create
  	@book = Book.create params[:book]
    if @book.valid?
      flash[:success] = 'Uspeno dodata knjiga!'
      redirect_to root_path
    else
      flash[:error] = 'Doslo je do greske! Popunite obavezna polja.'
      render :new 
    end   
  end

  def edit
  	@book = Book.find params[:id]
  end

  def update
  	book =  Book.find params[:id]
  	if book.update_attributes params[:book]
      flash[:success] = 'Uspeno izmenjena knjiga!'
  		redirect_to books_path
  	else
  		flash[:error] = 'Doslo je do greske! Popunite obavezna polja.'
      redirect_to :back
  	end		
  end

  def destroy
  	Book.destroy params[:id]
    flash[:success] = 'Uspeno izbrisana knjiga!'
  	redirect_to books_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :authorized, :only => :new


def create
	session[:password] = Digest::SHA256.hexdigest(params[:password])
	if admin?
		flash[:success] = "Dobrodosli, ostvarili ste administratorske privilegije"
	else
		flash[:error] = "Pogresna sifra, pokusajte ponovo"  	
	end
	redirect_to root_path
end


def destroy
  reset_session
  flash[:success] = "Uspesno ste se odjavili"
  redirect_to root_path
end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/books_helper.rb
module BooksHelper
	def title(page_title)
		content_for (:title ) { page_title }
	end
	def yield_or_default(section, default = "")
		content_for?(section) ? content_for(section) : default
	end
	
	def categories
		@cat = Array.new
		categories = Book.select('distinct categories').collect(&:categories)
		categories = categories.collect{|x| x.split(",")}.flatten!.collect{|x| x.strip.downcase}.uniq!
		@cat=categories.sort!
	end
	def authors
		@auth = Book.select('distinct author').collect(&:author).sort!
	end
end	

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/books/_comments.html.erb
<div class="row">
	<div class="span12" id="disqus_thread">Disqus!</div>
</div>

app/views/books/_form.html.erb
	<div class="row">
		<%= form_for @book, :html => {:multipart => true,:class=>"form-horizontal span12"} do |f| %>

	 		<fieldset class="row">
	 			<div class="control-group ">
	 				<%= f.label :Naslov, :class=>"control-label" %>
	 		    	<div class="controls">
 		    		 	<%= f.text_field :title, :class=>"span6" %>
	 		    		<p class="help-block"><span>*</span> Obavezno polje</p>
	 		    	</div>
	 		   </div>
	 		   <div class="control-group ">
		 		     <%= f.label :Autor_dela, :class=>"control-label" %>
		 		    <div class="controls">
		 		    	<%= f.text_field :author, :class=>"span6", :data => {:provide=> 'typeahead'}, :autocomplete => 'off' %>
		 		    	<p class="help-block"><span>*</span> Obavezno polje</p>
		 		    </div>
		 	   	</div>
	 		   <div class="control-group ">
 			     	<%= f.label :Kategorija, :class=>"control-label" %>
	 			    	<div class="controls">
	 			    		<%= f.text_field :categories,:class=>"span4", :data => {:provide=> 'typeahead'}, :autocomplete => 'off' %>
	 			    		<p class="help-block"><span>*</span> Obavezno polje, unete kategorije razdvojte zarezom</p>
	 			    	</div>
	 			</div>
	 			 <div class="control-group ">
		 		     <%= f.label :Jezik, :class=>"control-label" %>
		 		    <div class="controls">
		 		    	<%= f.select :lang, ["Srpski","Engleski"], :class=>'span4' %>
		 		    </div>
		 	   	</div>	
	 			<div class="control-group ">
	 		        <%= f.label :Informacije_o_knjizi, :class=>"control-label" %>
	 		        <div class="controls">
	 		        	<%= f.text_area :info, :class =>"span9", :id=>"textarea", :rows=>"10" %>
	 		        </div>
	 		    </div>
	 		    <div class="control-group ">
		 		    <%= f.label :Veb_adresa,:class=>"control-label" %>
		 		    <div class="controls">
						<%= f.text_field :webpage,:class=>"span6" %>
		 		    	<p class="help-block"><span>*</span> Obavezno polje</p>
		 		    </div>
		 	   	</div>  
	 		   	<div class="control-group form-inline txt-box">
	 			    <div class="row">
	 			    	<div class="span9 offset2">
 			    			<div class="span4">
 			    				<%= f.label :remote_image_url, "Izaberite sliku",:class=>"control-label" %>
 			    				<%= f.file_field :image, :class=>"input-file" %> 
 			    			</div>
	 			    		<div class="span4">
	 			    			<%= f.label :remote_image_url, "ili url slike",:class=>"form-url control-label" %>
     		    				<%= f.text_field :remote_image_url %>
		 			    	</div>
		 		    	</div>
						<% if @book.image.to_s != 'default.gif'%>
							<div class="span5 offset4 f-img">
								<%= image_tag @book.image_url(:thumb).to_s %>
								<%= f.label :remove_image, :class=>"checkbox" do%>
								<%= f.check_box :remove_image %>
								<p>Želite li da obrišete sliku?</p>
								<% end %>
							</div>
						<% end %>
		 		    </div>
	 		   </div>
	 		   <div class="span3 offset5">
	 		   		<%= f.submit :class=>"btn btn-primary"%>
	 		        <%= link_to "Obustavi", root_path, :method => "get", :class=>"btn" %>
	 		   </div>
	 		</fieldset>
		 <% end %>
	</div>

app/views/books/_share.html.erb
<div class="container">
	<div class="row">
		<div class="span4 offset4 addthis_toolbox addthis_default_style addthis_32x32_style">
			<a class="addthis_button_twitter"></a>
			<a class="addthis_button_facebook"></a>
			<a class="addthis_button_google_plusone_badge" g:plusone:size="medium" g:plusone:name="AddThis" g:plusone:href="https://plus.google.com/102383601500147943541/"></a>
			<a class="addthis_button_tumblr"></a>
			<a class="addthis_button_email"></a>
			<a class="addthis_button_compact"></a>
			<a class="addthis_counter addthis_bubble_style"></a>
		</div>
		<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4f91e0015320470e"></script>
	</div>
</div>

app/views/books/edit.html.erb
 <% title "Izmeni | Slobodna polica" %>
<div class="container">
	 <%= render 'form' %>	
 </div>

app/views/books/index.html.erb
<div class="hero-unit">
  <h1>Zdravo svete :)</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
  <%= render 'share' %>
</div>
<% for book in @books %>
<div class="book span6">
      <div class="row-fluid">
        <div class="span12">
          <div class="row-fluid">
            <div class="span6">
				<%= link_to book, :class=> 'thumbnail' do %>
					<%= image_tag book.image_url(:thumb).to_s %>
				<% end %>
            </div>
            <div class="span6">
            	<h3><%= link_to book.title, book%></h3>
            	<h4>Autor:</h4><p><%= book.author%></p>
            	<div class="desc">
            		<%= truncate(book.info, :length => 143, :separator => ' ')%>
            		<p><%= link_to 'saznaj više >', book%></p>
            	</div>
            	<pre class="link"><i class=" icon-bookmark"></i><%= link_to 'Veb stranica', book.webpage%></pre>
            </div>
          </div>
          <% if admin? %>
          <div class="book-adm row-fluid">
  	      	<div class="span6">
  	      		<%= link_to 'Izmeni', edit_book_path(book),:class => 'btn pull-right' %>
  	      	</div>
    	    	<div class="span6">
    	    		<%= link_to 'Obriši', book, :method => 'delete', :class =>'btn btn-danger' %>
    	    	</div>	 
          </div>
          <% end %>
        </div>
      </div>
</div>
<% end %>
<div class="span12"><%= will_paginate @books,:class => "pager" ,:page_links => false %></div>

app/views/books/new.html.erb
<% title "Dodaj | Slobodna polica" %>
<div class="container">
	<div class="hero-unit">
	  <h1>Dodaj knjigu</h1>
	  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	  proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
	</div>
<%= render 'form' %>
</div>

app/views/books/show.html.erb
<% title @book.title + " | Slobodna polica" %>

<div class="row">
	<div class="container">
		<% if admin? %>
			<div class="row">
				<div class="span12">
					<div class="row">
						<div class="span2 offset5">
							<%= link_to 'Izmeni', edit_book_path, :class => 'btn pull-right' %>
							<%= link_to 'Obriši', "#", :method => 'delete', :class =>'btn btn-danger' %></div>
					</div>
				</div>
			</div>
		<% end%>
		<div class="row">
			<div class="span8 book-heading">
					<h1><%= @book.title%></h1>
					<h3>Autor:&nbsp;<%= link_to @book.author, root_path(:search => @book.author )%></h3>
					<div class="row">
						<div class="span8">
							<h3>Kategorije: <%= link_to @book.categories.downcase, '#categories', :data => {:toggle=>"modal"}%></h3>
						</div>
					</div>
					<div class="row">
						<div class="span8">
							<h3><%= link_to @book.lang, root_path(:search => @book.lang)%>&nbsp;jezik</h3>
						</div>
					</div>
			</div>
			<div class="span4 book-img">
				<div class="row">
					<%= image_tag @book.image_url.to_s, :class=> 'thumbnail' %>
				</div>
			</div>
		</div>	
		<div class="row">
			<div class="span12 txt-box">
				<div class="row">
						<div class="span10 offset1"><p><%= @book.info%></p></div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="span12">
				<div class="row">
					<div class="span4 offset4"><pre class="link"><i class=" icon-bookmark"></i><%= link_to @book.webpage, @book.webpage%></pre></div>
				</div>
			</div>
		</div>
		<%= render 'share'%>
		<%= render 'comments'%>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer row-fluid">
	<div class="container">
		<p class="pull-right"><a href="#">Na vrh</a></p>
		<p>Designed and built with all the love in the world <a href="http://twitter.com/twitter" target="_blank">@twitter</a> by <a href="http://twitter.com/mdo" target="_blank">@mdo</a> and <a href="http://twitter.com/fat" target="_blank">@fat</a>.</p>
		<p>Code licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0" target="_blank">Apache License v2.0</a>. Documentation licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
		<p>Icons from <a href="http://glyphicons.com">Glyphicons Free</a>, licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
	</div>
</footer>

app/views/layouts/_modals.html.erb
<div class="modal fade" id="about">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h2>O policama..</h2>
  </div>
  <div class="modal-body">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
</div>

<div class="modal fade" id="categories">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>&nbsp;
  </div>  
    <div class="modal-body">
      <h2 class="span6">Jezik:</h2>
        <ul>
          <li class="span2"><%= link_to 'Srpski', root_path(:search => 'srpski' ) %></li>
          <li class="span2"><%= link_to 'Engleski', root_path(:search => 'engleski' ) %></li>
        </ul> 
      <h2 class='span6'>Kategorije:</h2>
      <p>
        <ul>
          <% for category in @cat %>
          <li class="span2"><%= link_to category, root_path(:search => category) %></li>
          <% end %>
        </ul> 
      </p>
      <h2 class='span6'>Autori:</h2>
      <p>
        <ul>
          <% for author in @auth %>
          <li class="span2"><%= link_to author, root_path(:search => author) %></li>
          <% end %>
        </ul> 
      </p>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Slobodna polica", root_path, :class => "brand span2" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse">
             <ul class="nav">
            	<li><%= link_to "Kategorije", '#categories', :data => {:toggle=>"modal"} %></li>
            	<li><%= link_to "Dodaj", new_book_path %></li>
            	<li><%= link_to "O projektu", '#about', :data => {:toggle=>"modal"} %></li>
              <% if admin? %>
                <li><%= link_to "Log out", logout_path %></li>
              <% end %>
            </ul>
            <form action="/" method="get" class="navbar-search pull-right">
              <%= text_field_tag :search, params[:search], :class=>"search-query", :placeholder=>"Pretraga" %>
            </form>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield_or_default(:title, "Slobodna polica")%></title>

  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
<link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
    <script type="text/javascript">
jQuery(document).ready(function() {
      var allCat = [<% for category in categories %>"<%= category %>",<% end %>];
      $('#book_categories').typeahead({source: allCat});
      var allAuth = [<% for author in authors %>"<%= author %>",<% end %>];
      $('#book_author').typeahead({source: allAuth});
    });
    </script>
<body>

<%= render "layouts/navbar" %>


<% flash.each do |name, massage| %>
  <div class="alert <%= "alert-"+name.to_s %>">
    <a class="close" data-dismiss="alert">×</a>
    <span class="badge <%= "badge-"+name.to_s %>">Obaveštenje:</span> <%=  massage%>
  </div>	
<% end %>

<div id="content" class="content"><%= yield %></div>

<%= render "layouts/footer" %>
<%= render "layouts/modals" %>
 
</body>
</html>